# Generated by Django 5.1.4 on 2025-01-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acc_email',
            field=models.EmailField(default='user@mail.com', max_length=254, unique=True),
        ),
    ]
